### ISSUE TITLE
Blurred Fonts and Images in high dpi....

### ISSUE THREAD

**Issue by IPeluchito** [jdennis9/ratmp#1]
At 3840x2160 resolution and 300% scaling in Windows 11 it looks like this:

![snip_00008](https://github.com/jdennis9/ratmp/assets/64821708/4c5b0174-4618-43b6-951e-8bfb09a34cdd)

**Comment by jdennis9** [comment]
4b284af4c2633eb7afd74cad49932e8d1e6a723f fixes this

**Comment by jdennis9** [comment]
4b284af4c2633eb7afd74cad49932e8d1e6a723f fixes this
